debian/conf/composer.json       usr/lib/raiffeisenbank-statement-downloader/
src/*			        usr/lib/raiffeisenbank-statement-downloader/
#src/SpojeNet/*                 usr/lib/raiffeisenbank-statement-downloader/SpojeNet/
bin/*                           usr/bin/
.env.example                    usr/share/doc/raiffeisenbank-statement-downloader
io.github.spoje_net.raiffeisenbank_statement_downloader.metainfo.xml /usr/share/metainfo/
raiffeisenbank-statement-downloader.svg            /usr/share/icons/hicolor/scalable/apps/
